# github_metrics.yml

name: GitHub Metrics
on:
  schedule:
    - cron: "0 8 1/2 * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: UnderCurve
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: yes
          config_display: columns
          config_octicon: yes
          config_timezone: America/Chicago
